---
author: "Josie Browning"
date: "2023-04-20"
title: "Screencast Pseudocode"
output: html
categories: project
---

- What was the average totality duration for the 2024 total solar eclipse by state
- Visual of totality of eclipse over a map
- Create a summary of the two partial eclipses seen in Missouri
- Compare the two partial eclipses with a graph

First Quest: What was the average totality duration for the 2024 total solar eclipse 
 - find length of totality as numeric
    - mutate to create a new column that subtracts the end time of totality from beginning time
    - change the datetime variable to as.numeric 
 - grouping by state, create a new column using mutate and use the mean function 

Second Quest: Visual of totality of eclipse over a map
- use the same column of length of totality as numeric 
- Using some map data from hw 5
  - map <- map_data("world") %>%
  filter(region %in% c("USA"))
  - looking at eclipse_total_2024
    - get length of totality in seconds 
    - mutate for end - beginning, and as.numeric 
  - x and y axis are long and lat from map data (geom_polygon)
  - x and y axis are lon and lat grouped by eclipse_3 (geom_point)
  - use Cartesian coordinates

Third Quest: Creating a summary of the partial eclipses seen in Missouri
- filter the two partial eclipses by state for only Missouri data
- find total length of both eclipses, mutate
- join together the two data frames, inner join by name
- find difference between duration, mutate
- transform seconds into minutes

Fourth Quest: Compare the two partial eclipses with a graph 
- join the two partial eclipse datasets
  - create a common key to prevent confusion
- create new columns for duration of the two eclipses
- pivot longer so we can graph the data
  - names to year column
  - values to duration column
  - rename columns to 2023 and 2024 duration
- line graph
  - x is our state and name key column 
  - y is duration 
  - color and group by year
  - geom_line
  
